- provider/cgi.go
- provider/http.go
- provider/provider.go
> add http provider

- core/motan.go
- core/url.go
- endpoint/motanEndpoint.go
- metrics/meter.go
- server/server.go
fix gzip
add miss func for go-metrics new version
> fix gzip;add miss func for go-metrics new version

- agent.go
- core/globalContext.go
- provider/http.go
- provider/provider.go
http provider support multiple url config as a service group for weibo mesh.
> http provider support multiple url config

- agent.go
- main/serverdemo.go
- server.go
add service available/unavailable for agent or server
> add service available/unavailable

- provider/cgi.go
- provider/http.go
> Httpprovider default conf

- agent.go
- client.go
- cluster/command.go
- config/config.go
- config/config_test.go
- config/testconf.yaml
- core/globalContext.go
- core/motan.go
- endpoint/grpcEndpoint.go
- filter/accessLog.go
- filter/metrics.go
- main/clientdemo.go
- metrics/graphite.go
- protocol/motanProtocol.go
- provider/cgi.go
- provider/http.go
- serialize/simple.go
- serialize/simple_test.go
feature:
1.  add handler register for agent manage
2. support dynamic config
3. add mulit param serialize for simple serialization
bugfix:
1. fix http reverse proxy
2. fix serviceListener notify NP(Nil Pointer)
> Merge multi feature

- agent.go
- client.go
- core/url.go
- endpoint/endpoint.go
- endpoint/motanEndpoint.go
- protocol/motanProtocol.go
- protocol/motanProtocol_test.go
- serialize/simple.go
- server/motanserver.go
optimise protocol parse, simple serialization, and motan endpoint
> optimise motan endpoint

- core/bytes.go
- serialize/simple.go
- serialize/simple_test.go
remove unsigned types，change int8 to byte
> change simple serialization supported types

- registry/zkRegistry.go
> fix zk registry init

- provider/provider.go
- registry/zkRegistry.go
1. Zk registry recognizes java command error.
2. SubscribeCommand synchronization problem.
3. CreatePersistent recursively creating nodes problem.
4. Optimize variable naming and error logging.
> Fix some zk registry bugs & Optimize some problems

- agent.go
- config/config.go
- core/globalContext.go
- filter/circuitbreaker.go
- glide.yaml
Fix: 
1. When the service starts, if do not specify the pool parameter, the service exits abnormally.
2. When getting the configuration, sometimes get nil pointer exception.
Optimize:
1. error messages
> fix dynamic config bugs & optimize

- core/constants.go
- endpoint/motanEndpoint.go
- server/motanserver.go
> fix conn write timeout

- cluster/motanCluster.go
- core/url.go
- filter/accessLog.go
- filter/filter.go
- filter/rateLimit.go
- filter/rateLimit_test.go
- manageHandler.go
- server/server.go
Mainly includes the following 2 parts:    
- Add local rateLimit filter based on token-bucket
- Provide service rateLimit, method rateLimit, and the switcher functions
- Include unit test
- Add protection mechanism when NewFilter returns nil
> Add a local rateLimit filter

- protocol/motanProtocol.go
- protocol/motanProtocol_test.go
> gzip with buffer pool

- endpoint/motanEndpoint.go
- protocol/motanProtocol.go
- server/motanserver.go
When as a proxy server, this program will reuse the requestID from client,
and the requestID is the communication identifier for a tcp channel.
The reverse proxy server will have the same requestID from different clients,
but those requests may use a same channel when send to then backend server.
Here we use a different id as the communication identifier.
> Fix: reverse proxy duplicate requestID result wrong response.

- agent.go
- cluster/httpCluster.go
- cluster/motanCluster.go
- core/globalContext.go
- core/motan.go
- core/ping.go
- http/httpProxy.go
- http/httpProxy_test.go
- http/script.go
- main/agentdemo.go
- main/agentdemo.yaml
- main/serverdemo.yaml
- provider/httpProvider.go
- server/httpProxyServer.go
> Http mesh fix

- core/globalContext.go
- server/httpProxyServer.go
> adjust http mesh configuration convention

- .travis.yml
- core/switcher_test.go
- metrics/graphite_test.go
- metrics/metrics.go
- metrics/metrics_test.go
- protocol/motanProtocol_test.go
> resolve metrics data race

- protocol/motanProtocol.go
- protocol/motanProtocol_test.go
fix gzip buf concurrent problem
> fix gzip buf concurrent problem

- core/debug.go
- core/motan.go
- endpoint/motanEndpoint.go
- manageHandler.go
- server/motanserver.go
1. Add 6 spans for the Trace 
- `convert` (`response_spans`)
- `epFilter` (`response_spans`)
- `clustFilter` (`response_spans`)
- `requestTime` (`values`)
- `responseTime` (`values`)
- `remoteTime` (`values`)
2. Optimize print structure of the Trace
- Put the `values` above the `response_spans` and `request_spans`
> Add 6 values for the Trace & Optimize print structure of the Trace

- endpoint/motanEndpoint.go
- server/motanserver.go
SetNoDelay(true) for every TCP connection.
> SetNoDelay true

- endpoint/motanEndpoint.go
You can change `errorCountThreshold` and `keepaliveInterval` in configFile for motanEndpoint.
> export `errorCountThreshold` and `keepaliveInterval` config key

- agent.go
New feature: you call service without group parameter when the service belongs to only one group.
> New feature: call service without group parameter

- agent.go
- agent_test.go
- cluster/motanCluster.go
- ha/failoverHA.go
- manageHandler.go
Handle nil motanCluster in clusterMap (caused by  https://github.com/weibocom/motan-go/pull/145)
> Handle nil cluster in clusterMap

- agent_test.go
- server/httpProxyServer.go
- server/motanserver.go
- testdata/agent.yaml
…st body size of fasthttp is 4M, this may be not enough
> [http] Support configure max request body size

- .travis.yml
- cluster/motanCluster.go
- core/constants.go
- filter/accessLog_test.go
- filter/clusterMetrics.go
- filter/metrics.go
- filter/metrics_test.go
- ha/backupRequestHA.go
- ha/backupRequestHA_test.go
- ha/failoverHA.go
- server/httpProxyServer.go
1. MotanCluster add default attachments
2. BackupRequest escape metrics key
> Fix attachments and metrics key

- ha/backupRequestHA.go
- metrics/graphite.go
1. Fix backupRequest does not get the second node through loadBalance, which causes the nodes of the second request to be concentrated in one interval.
2. Set the overall timeout for backupRequest.
3. Reuse the port in UDP socket.
> Fix 3 problems

- go.mod
- serialize/breeze.go
> update breeze to v0.1.0

- metrics/metrics.go
- metrics/metrics_test.go
add ReadonlyStatItem for metrics
> add ReadonlyStatItem for metrics

- server/motanserver.go
> Revert "fix response not set process time"

- client.go
- client_test.go
add support of new client from config object
> Client from config

- README.md
- agent.go
- agent_test.go
- core/map.go
- core/url.go
- default.go
- manageHandler.go
- server_test.go
- testdata/agent-reload.yaml
use `/reload/clusters` for hot reload clusters config
1. update config file.
2. request `/reload/clusters`
> support agent clusters config hot reload

- agent.go
- endpoint/motanEndpoint.go
agent add the ability to customize handler to processing command.
> agent add the ability to customize handler to processing command

- agent.go
- endpoint/motanEndpoint.go
agent add the ability to customize handler to processing command.
> agent add the ability to customize handler to processing command.

- http/httpProxy.go
- http/httpRpc_test.go
fix httpproxy Content-Type problem
> Fix httpproxy contenttype

- .gitignore
- core/constants.go
- core/globalContext.go
- core/globalContext_test.go
- core/testdata/applications/globalFilter.yaml
- core/testdata/services/motan.TestGlobalFilterService1.yaml
- core/testdata/services/motan.TestGlobalFilterService2.yaml
- core/testdata/services/motan.TestGlobalFilterService3.yaml
- core/util.go
- log/rotate.go
- log/rotate_notwin.go
- log/rotate_win.go
fix #257
* filter支持全局配置
* support windows build
* log dir permission set 0755
> filter支持全局配置

- agent.go
- agent_test.go
- client.go
- client_test.go
- go.mod
- log/filter.go
- log/filter_test.go
- log/log.go
- server.go
- server_test.go
filter channel
filter unit test
filter unit
> log filter

- metrics/graphite.go
- metrics/graphite_test.go
fix: reconnect graphite connection every write interval
> reconnect graphite udp connection every write interval

- agent.go
- default.go
- manageHandler.go
- manageHandler_test.go
1. add get all service interface
2. expose agent dynamic register service
> Add get all services

- http/httpProxy.go
- http/httpProxy_test.go
- http/httpRpc_test.go
> http proxy header:host

- agent.go
- core/constants.go
- core/map.go
- core/url.go
- endpoint/motanCommonEndpoint.go
- endpoint/motanCommonEndpoint_test.go
- endpoint/motanEndpoint.go
1. 并行初始化cluster
2. 建连增加延迟和异步的逻辑，并可配置
3. 补充单测
> agent 启动提速

- endpoint/motanCommonEndpoint.go
- endpoint/motanEndpoint.go
- provider/httpxProvider.go
1. Correct spelling mistake
2. fix nil conn entering assertion bug in Motan endpoint and Motan Common endpoint, which could cause panic.
> fix endpoint nil conn enter assertion bug

- agent_test.go
- log/log.go
> export log dir

- agent_test.go
- cluster/motanCluster.go
- core/util.go
- core/util_test.go
- ha/backupRequestHA_test.go
- server/server.go
> log filter init info

- agent.go
- agent_test.go
metric: not found provider count
> not found provider count

- cluster/motanCluster.go
- cluster/motanCluster_test.go
- core/constants.go
- core/util.go
- core/util_test.go
- protocol/motan1Protocol.go
- registry/directRegistry.go
- registry/directRegistry_test.go
- registry/zkRegistry.go
Configure direct services through environment variables;
Add additional warn info for protocol v1 exception;
DirectRegistry supports specifying group;
Fix some typos
> Configure direct services through environment variables

- provider/httpProvider.go
http_privoder: support upstreamCode attachment
> support http_provider upstream_code

- agent.go
- core/constants.go
- core/motan.go
- endpoint/motanCommonEndpoint.go
- endpoint/motanEndpoint.go
- provider/httpProvider.go
- provider/httpxProvider.go
- provider/motanProvider.go
- provider/motanProvider_test.go
set remote address in response in proxy mode
> set remote address in response in proxy mode

- core/bytes.go
- endpoint/motanCommonEndpoint.go
- endpoint/motanEndpoint.go
- metrics/metrics.go
- server/motanserver.go
endpoint.stream & core.bytesbuffer object reuse
> reuse bytesbuffer & stream

- endpoint/motanCommonEndpoint.go
- endpoint/motanEndpoint.go
> stream reuse bugfix

- core/bytes.go
- endpoint/motanEndpoint.go
- filter/accessLog.go
- filter/metrics.go
- log/bytes.go
- log/bytes_test.go
- log/log.go
- protocol/motanProtocol.go
- server/motanserver.go
* Profile base do accesslog (#343)
> Profile base timenow (#344)

- core/url.go
- core/url_test.go
- endpoint/motanCommonEndpoint.go
- protocol/motanProtocol.go
> add url int param cache

- client.go
- client_test.go
- core/motan.go
- endpoint/endpoint.go
- endpoint/motanCommonEndpoint.go
- endpoint/motanCommonEndpoint_test.go
- endpoint/motanEndpoint.go
- endpoint/motanEndpoint_test.go
> fix_rpc_async_call

- agent.go
- metrics/metrics.go
> Fix report (#378)

- core/switcher.go
- core/switcher_test.go
- protocol/motan1Protocol.go
print decoding exception log through switch control
> print decoding exception log through switch control

- core/constants.go
- core/globalContext.go
- core/globalContext_test.go
- dynamicConfig.go
- dynamicConfig_test.go
support group suffix env.
register group with suffix replace old group.
subscribe new group with suffix.
> group suffix

- metrics/metrics.go
- protocol/motanProtocol.go
> Optimize metrics lock release

- core/constants.go
- core/url.go
- core/url_test.go
- dynamicConfig.go
make motanV1Compatible compatible with motan2, motan and motanV1Compatible
> modify canServe
